language: cpp

sudo: false

cache:
  directories:
  - toolchain

matrix:
  exclude:
    - os: linux
  include:
    - os: linux
      env: MASON_PLATFORM=linux BUILDTYPE=Debug
      compiler: clang

env:
  global:
   - TERM: dumb

addons:
  apt_packages:
  - gdb # for printing stack traces from core dumps
  - xutils-dev
  - libxxf86vm-dev
  - x11proto-xf86vidmode-dev

before_install:
- source ./scripts/setup_mason.sh
- source ./scripts/travis_helper.sh
- source ./scripts/flags.sh

install:
- source ./scripts/install_node.sh
- source ./scripts/install_awscli.sh
- if [[ ${MASON_PLATFORM} == "linux" ]]; then ./scripts/setup_cxx11.sh; source ./toolchain/env.sh ; fi
- ./scripts/install_${MASON_PLATFORM}.sh

script:
- ./scripts/run_${MASON_PLATFORM}.sh

git:
  submodules: false
